### ISSUE TITLE
how admin can update user meta using gravity forms

### ISSUE THREAD

**Issue by ookdevil** [eugelogic/gatsby-press#62]
Hi Guys,

I am using Gravity Formas user registration addon I can update user meta of the logged-in user only but I want also to update user meta whenever admin fills a form by entering user Email in the Email field.
Whenever Admin fills a form and enters email id which is users' email and all the populated fields should be updated to the user holding the Email.

Please give a golden or suggest a plugin
Thanks
Aman Kumar Shah

**Comment by eugelogic** [comment]
Hi [ookdevil](https://github.com/ookdevil),

Sorry I haven't got that far with Gravity Forms yet.

**Comment by eugelogic** [comment]
Hi [ookdevil](https://github.com/ookdevil),

you could try your luck on https://github.com/robmarshall/gatsby-source-gravityforms
